social:        
    facebook:
        url: 'https://www.facebook.com/'
        icon:
            inner: fa-facebook-f
            outer: fa-circle
    twitter:
        url: 'https://twitter.com/'
        icon:
            inner: fa-twitter
            outer: fa-circle
    googleplus:
        url: 'https://plus.google.com/'
        icon:
            inner: fa-google-plus
            outer: fa-circle
    youtube:
        url: 'https://www.youtube.com/'
        icon:
            inner: fa-youtube
            outer: fa-circle        
    pinterest:
        url: 'https://www.pinterest.com/'
        icon:
            inner: fa-pinterest-p
            outer: fa-circle       
   
    blog:
        url: '/blog/'
        icon:
            inner: fa-rss
            outer: fa-circle       

                   
        

company:
    name: Fifth Gear Marketing
    address:
        street: Street       
        province: Province       
        country: Country
phone:
    toll: 888.000.0000
    reception: 250.000.0000  
    
    
email:
    info: info@fifthgeardev.com
    
    
settings:
    slideshow:
        home:
            template: 'slideshow-home'
        logo:
            url: /wp-content/themes/wp-theme-fg-child/assets/images/templates/logo.png
            alt: Logo
    page:
        grid:
            left: col-sm-12
           
             
    footer:
        grid:
            left:  col-lg-6 col-lg-push-6 
            right: col-lg-6 col-lg-pull-6
        logo:
            url: /wp-content/themes/wp-theme-fg-child/assets/images/templates/logo.png
            alt:
        social:
            enable: true

            
    copyright:
        grid:
            left:  col-lg-6 col-lg-push-6 
            right: col-lg-6 col-lg-pull-6
        text: ', Fifth Gear Marketing'
        year: 2017
    modal:
        logo: /wp-content/themes/wp-theme-fg-child/assets/images/templates/logo.png
        
postid:
    terms: 13
    privacy: 16
    contactmodal: 35
        
forms:
    footer:
        
        
        
        
slideshow:
    home:
        id : homepage-slideshow
        controls : false
        indicators : true
        captions : false
        titles : false
        interval: 6000
        outer_class : feature-carousel carousel-fade
        items:
gallery:
    home:
        directory : 
            root : '/wp-content/themes/wp-theme-fg-child/assets/images/gallery/'
            thumbs : 'thumb/'
            medium : ''
            large : 'large/' 
        class : 'script-grid-gallery gallery-grid-20'
        filter : 
            enable : false       
        filters :
            -
                title : 'Videos'
                slug : 'video'
            -
                title : 'Test'
                slug : 'test'
        options : 
            group : homepage
            hover : true            
            thumbsperrow : 5
            thumbpadding : 0
            random : false
            enable:
               
        images : 
